version: '3.2'

services:
   db:
      image: mysql:latest
      container_name: appsDB
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '1234'
    

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
   