
UPDATE Ship SET S_Name='UPDATED NAME!', PrevPort='UPDATED PORT!' WHERE ShipID=1;
UPDATE Ship SET S_Name='AN UPDATED NAME!', PrevPort='YET ANOTHER UPDATED PORT!' WHERE ShipID=2;

DELETE FROM Tanker WHERE TankID=3;
